#!/usr/bin/python
# -*- coding: utf-8 -*-

import argparse

parser = argparse.ArgumentParser()
parser.add_argument('file',
        help="input file")
parser.add_argument('-o', '--output',
        default='output',
        help="output file")
parser.add_argument('-a', '--addr',
        help="cut address [start_address]:[end_address]")

args = parser.parse_args()

if args.addr == None:
    print "need -a option"
    exit()

rf = open(args.file, 'rb')
wf = open(args.output, 'wb')

addr = args.addr.split(":")

if len(addr) == 2:
    if addr[0] == "":
        start_addr = None
        if "0x" in addr[1]:
            end_addr = int(addr[1], 16)
        else:
            end_addr = int(addr[1], 10)
    elif addr[1] == "":
        end_addr = None
        if "0x" in addr[0]:
            start_addr = int(addr[0], 16)
        else:
            start_addr = int(addr[0], 10)
    else:
        if "0x" in addr[1]:
            end_addr = int(addr[1], 16)
        else:
            end_addr = int(addr[1], 10)
        if "0x" in addr[0]:
            start_addr = int(addr[1], 16)
        else:
            start_addr = int(addr[1], 10)
else:
    print parser.print_help()
    exit()


data = rf.read()[start_addr:end_addr]

wf.write(data)
